### ISSUE TITLE
fatal: Not a Git repository

### ISSUE THREAD

**Issue by Inmovilizame** [Shaggy13spe/gitflow4code#1]
Hello, 

I am using this extension v0.0.5 with VSCode 1.12.2 on MacOSX 10.12. 

When I press the feature test button of the bottom bar an error message arises "hello command not found". If I try to use is through the command palette a different error is throw to the GIT output: 

  "fatal: Not a git repository (or any of the parent directories): .git"

Of course the folder is a git repo and has git flow initialized, I was able to manage it through command line. May it be some misconfiguration, seems to me like this extension is trying to run on a different directory

**Comment by Shaggy13spe** [comment]
Hello, sorry for getting back to you so late...I haven't actually fully implemented the "feature test" button yet.
As for the error you are getting, I had seen it before, but only when I wasn't in the actual git repo folder. If you are sure you are in fact in the repo, I'm not sure why it would fail. I'll look in to it.

**Comment by Inmovilizame** [comment]
Don't worry :) thank you for answering. 

If there is anything I can do, or something to test on my computer, to help you let me know.

**Comment by Shaggy13spe** [comment]
issue fixed in 0.1.0
