### ISSUE TITLE
Not working on 1.17

### ISSUE THREAD

**Issue by codecrafting-io** [Shaggy13spe/gitflow4code#2]
I don't know what is happening, but its literally not working for me. Nothing happens when I try to create a new release or feature. Even looking to the console nothing happens too. I did initialize the gitlfow. I am using git 2.14.2 on a windows machine with the 1.17 version of vscode.

**Comment by Shaggy13spe** [comment]
Hello, sorry for not getting back to you sooner. Are you still having issues? If so, can you provide any screenshots of the steps you are taking and any errors received?

**Comment by Shaggy13spe** [comment]
Closing due to no response from OP
