### ISSUE TITLE
Can not create Release branch due to branch name constrictions

### ISSUE THREAD

**Issue by MuratOzsoyler** [Shaggy13spe/gitflow4code#24]
I couldn't create a Release "0.1.0" branch. The message in output log was:
```
Branch name has illegal characters
A branch name can not:
	- Have a path component that begins with "."
	- Have a double dot ".."
	- Have an ASCII control character, "~", "^", ":" or SP, anywhere
	- End with a "/"
	- End with ".lock"
	- Contain a "" (backslash))
```

However I can open Release branches like this name, under Visual Studio 2017/2019 gitflow extension. Is there a configuration parameter that I can tweak with?

Thank you for this great extension.

**Comment by MuratOzsoyler** [comment]
I also tried and couldn't creat Release named "release-0.1.0".

**Comment by MuratOzsoyler** [comment]
It seems that release name can not contain `.` caharacter. I can create releases names `release-0_1_0` or `0_1_0`.

**Comment by Shaggy13spe** [comment]
Sorry, I will look into this. Unfortunately, I have been so busy with both my work and personal life, I haven’t had much time to devote to this project as I’d like to.

**Comment by MuratOzsoyler** [comment]
Thank you for the answer.

I've just seen that the problem is solved in the `develop` branch. So I think I'll wait for the next version.

Closing this issue.

**Comment by throrin19** [comment]
Any news of the deployment of this version ? Same problem here
