### ISSUE TITLE
Ability to switch application while naming feature

### ISSUE THREAD

**Issue by kristiannotari** [Shaggy13spe/gitflow4code#7]
I found that when naming a feature (or something else) I'd like to switch application and check for example, if what I'm typing is correct. At this time, switching application simply close my feature naming panel.

In the previous versions I also noticed some errors logged when this thing happened (maybe when the input was left blank, something about null reference etc). Now they're not there when I switch application, but still, input disappears and I have to give the command again. Also when switching, it created the feature (or something else) with the name I left in the input, maybe incomplete. 

Thanks,
Kristian

**Comment by Shaggy13spe** [comment]
As far as I know, that is just the default behavior of VS Code. They made the command pallet itself "sticky" several versions ago, but not pick lists or input boxes shown thereafter. I did add a bug fix a while back to only create the branch if an actual value is given (no empty string), however, there isn't really anything I can do about it creating it when you haven't finished typing if you move away from the IDE before finishing, as IDE itself just sends me the string you have and not an "escape" action, so there isn't a way for me to differentiate. I'll leave this open for now to investigate if there is something that can be done, but don't really think there is as I've tried to "correct" this behavior in the past.

**Comment by kristiannotari** [comment]
Didn’t know that behaviour. However I’m not 100% sure but I’ve seen the desired behaviour in another command, maybe ones related to git (that I think are Vscode integrated now and not 3rd party extensions) like git clone which let the input state panel there also if you switch application.

Don’t know how extensions and vscode talks each other so can’t help further :(

**Comment by Shaggy13spe** [comment]
So I found out there is an option that allows the inputbox to stay visible when switching to a different window. Will have it in the next release.
