### ISSUE TITLE
Cannot insert closing brackets "}" in editor

### ISSUE THREAD

**Issue by fatbitx** [Shaggy13spe/gitflow4code#9]
I'm using VSCode Insiders, and after installing this extension, I cannot insert the closing bracket "}" in the editor. I'm using a Spanish keyboard, so I need "AltGr + }" keypress. I love the extension, but this problem makes it unusable. It probably affects other symbols, but after a quick test this is the one I found. By the way, thanks for the extension.

**Comment by Shaggy13spe** [comment]
Hello, thanks for reporting the issue. I don't use the Insiders build, nor do I build/test against it so I can't really vouch for the extension's stability against it. I will try to take a look at this however. Can you tell me what the Gr in the key combo AltGr+} is?

**Comment by fatbitx** [comment]
Hi, well, that Gr is because in Spanish keyboards (maybe with other languages too), we have a key labelled AltGr (kind of "Alt Graphics"), placed next to the space key on the right side. I think the problem arises also in normal VSCode, not only the Insiders. So I'm glad to say it's not your fault, nor your extension. However, a workmate found a solution:

In the case you're suffering from this, go edit your keybindigs (keybindings.json), and add the following entry:

    // Fixes "the thing" with '}'
    {
        "key": "ctrl+alt+oem_2",
        "command": "type",
        //"when": "editorTextFocus",
        "text": "}"
    }

Thanks for your support, and keep rocking!
